# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Influence Function R
#' 
#' Influence function of the Kaplan-Meier estimator at time t. Specifically,
#' \eqn{\psi_{i}(t) = -S(t)\int_{0}^{t} dM_{i}(u) / Y(u)}.
#' 
#' @param status Status, coded as 0 for censoring, 1 for death.
#' @param time Observation time.
#' @param trunc_time Truncation time.
#' @return Data.frame.
InfluenceKM <- function(status, time, trunc_time) {
    .Call(`_SurvUtils_InfluenceKM`, status, time, trunc_time)
}

