# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate CIC
#'
#' Estimate the cumulative incidence curve. Specifically:
#' \eqn{F_{1}(t) = P(T \leq t, \delta = 1).}
#' 
#' @param status Status, coded as 0 for censoring, 1 for an event, 2 for death.
#' @param time Observation time.
#' @return Data.frame containing the tabulated cumulative incidence curve.
CalcCIC <- function(status, time) {
    .Call(`_SurvUtils_CalcCIC`, status, time)
}

#' CIC Influence Function
#'
#' Influence function for the cumulative incidence of the status == 1 event.
#' 
#' @param status Status, coded as 0 for censoring, 1 for an event, 2 for death.
#' @param time Observation time.
#' @param trunc_time Time at which to evaluate the influence function.
#' @return Vector of per-subject influence function evaluations.
InfluenceCIC <- function(status, time, trunc_time) {
    .Call(`_SurvUtils_InfluenceCIC`, status, time, trunc_time)
}

#' Calculate Restricted Mean Survival Time
#'
#' @param status Status, coded as 0 for censoring, 1 for death.
#' @param time Observation time.
#' @param extend Extend AUC calculation if tau exceeds max(time)?
#' @param tau Truncation time.
#' @return Numeric restricted mean survival time.
#' @export
RMST <- function(status, time, extend = FALSE, tau = NULL) {
    .Call(`_SurvUtils_RMST`, status, time, extend, tau)
}

#' Kaplan-Meier Influence Function
#' 
#' Influence function of the Kaplan-Meier estimator at time t. Specifically,
#' \eqn{\psi_{i}(t) = -S(t)\int_{0}^{t} dM_{i}(u) / Y(u)}.
#' 
#' @param status Status, coded as 0 for censoring, 1 for death.
#' @param time Observation time.
#' @param trunc_time Truncation time.
#' @return Numeric vector of influence function values for each observation.
InfluenceKM <- function(status, time, trunc_time) {
    .Call(`_SurvUtils_InfluenceKM`, status, time, trunc_time)
}

#' RMST Influence Function
#' 
#' Influence function of the restricted mean survival time at time t. Specifically,
#' \eqn{\psi_{i}(t) = -S(t)\int_{0}^{t} \mu_{\tau} dM_{i}(u) / Y(u)}.
#' 
#' @param status Status, coded as 0 for censoring, 1 for death.
#' @param time Observation time.
#' @param trunc_time Truncation time.
#' @return Numeric vector of influence function values for each observation.
InfluenceRMST <- function(status, time, trunc_time) {
    .Call(`_SurvUtils_InfluenceRMST`, status, time, trunc_time)
}

